apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-a
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-a-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-a-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: service-account-a
    namespace: default
roleRef:
  kind: Role
  name: service-a-role
  apiGroup: rbac.authorization.k8s.io